### ISSUE TITLE
Roadmap for getting volunteers involved

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/old_site#157]
Document detailing what to do with volunteers who get in touch with us. Can also be a better 'Get Involved' note for website.

**Comment by GrahamSteel** [comment]
As in re-writing this ? http://contentmine.org/#who

**Comment by jcmolloy** [comment]
Yes - it's really out of date! 

Also, some specific documentation for internal use which details the process for dealing with volunteers e.g.
Receive email from person interested in helping with coding
Send welcome email directing to quickscrape and OpenFarm as possible projects (you could write a template for this)
Ask if they will sign up to the contentmine-community mailing list
Follow them on Twitter from @TheContentMine
Schedule a follow up email for 2 weeks down the line to see if they need help
Schedule follow up emails at suitable intervals

The above is just an example! The way we do with will definitely evolve but if it's documented it's easier for you to follow and for anyone else if e.g. you're on holiday or away.

I'm happy to read drafts and reply to any questions on Slack (not promising I'll know the answer as we're still working out how the CM/Open Farm relationship will work)
