### ISSUE TITLE
Report on workshop sign-ups

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/old_site#176]
e.g. how many from:
Each institution
Each discipline

**Comment by GrahamSteel** [comment]
[TEST] (https://guides.github.com/features/mastering-markdown/)

**Comment by GrahamSteel** [comment]
This one was resolved via email and Slack.

**Comment by jcmolloy** [comment]
Hi Graham, a one-pager on the internal github or in a googledoc would be great, you should be able to make a doc in the ContentMine folder containing the Wellcome docs. I especially think we should properly document how many people signed up from each institution if known (inc. from UCL!)  so we can follow up for further workshops.  I know you posted this in Slack, but having it somewhere more permanent would be helpful. Here is the folder:
https://drive.google.com/drive/u/0/folders/0B9V3tIqIu0UZTjdVOTMxNTUtM2c/0B9V3tIqIu0UZfjdwNUprUUQySzFseTliSkZKckZSOS1fNk1Xbjc5eWkydm9hYkczQU5yUmM
