### ISSUE TITLE
Publicity for EBI hackday

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/old_site#191]

**Comment by GrahamSteel** [comment]
What and where is the EBI Hackday ?

**Comment by jcmolloy** [comment]
At EBI ;-)
It is one of the one's described in the project schedule:
https://github.com/jcmolloy/ContentMine-Internal/blob/master/ProjectSchedule.md

It's assigned this issue to a milestone which will have more details on
which one it is, but feel free to change the title to be more precise if it
helps! Some of these issues are attached to milestones that aren't due
until towards the end of the year.
