### ISSUE TITLE
Norma pitch on website

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/old_site#199]

**Comment by rossmounce** [comment]
Why we need normalized scholarly literature post. For readers, publishers, funders, pen-drives etc

**Comment by petermr** [comment]
what is projected size (a) text only (b) with images of (a) all the open
literature (b) just PLoSONE (c) just one year

On Wed, Feb 4, 2015 at 10:13 AM, Ross Mounce <notifications@github.com>
wrote:

> Why we need normalized scholarly literature post. For readers, publishers,
> funders, pen-drives etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/site/issues/199#issuecomment-72830229>.
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069
