### ISSUE TITLE
Content mine facts for topics on wikipedia? 

### ISSUE THREAD

**Issue by JosephMcArthur** [ContentMine/old_site#232]
Open Access Reader (https://meta.wikimedia.org/wiki/Open_Access_Reader) is currenlty planing on using CORE to pull in papers to be cited in wikipedia. Feels like the Content mine could also be useful here. 

One for you @GrahamSteel 

Full explanation sent in an email to Jenny 
>"I'm sure you're both familiar with the Open Access Reader project Ed Saperia is running. If you need a refresher, he's trying to get open access papers more cited in Wikipedia. One part of his project requires a chunk of the literature to be searched for information relevant to the wiki page and delivered to the editors easily. I'm sure you can see where I'm going with this... it feels like The Content Mine pipeline could easily do this around various keywords to deliver a stream of facts that could be cited as is, or with minimal changes. I keep having Jenny's line about seeing sentences in plant paper abstracts as totally copy and pastable into wikipedia running through my head. This would be good for you since it's only Open Access papers, so no legal barriers, and you'll be developing and supporting existing communities that you care about - even better if you're dumping the facts in Wikidata. Another interesting possibility, although this is getting into a realm I don't know much about, is automatically creating Content Mine feeds for Wikipedia pages from their titles and "sciency" words in the introduction."

**Comment by petermr** [comment]
Great, Jo,
I've talked a lot with Ed. Wikipedia has several scattered activities in
this area and I have also talked with Magnus Manske and the Cambridge
Wikipedians who are also very interested.

On Mon, Feb 9, 2015 at 8:30 PM, Joseph McArthur <notifications@github.com>
wrote:

> Open Access Reader (https://meta.wikimedia.org/wiki/Open_Access_Reader)
> is currenlty planing on using CORE to pull in papers to be cited in
> wikipedia. Feels like the Content mine could also be useful here.
>
> One for you @GrahamSteel <https://github.com/GrahamSteel>
>
> Full explanation sent in an email to Jenny
>
> "I'm sure you're both familiar with the Open Access Reader project Ed
> Saperia is running. If you need a refresher, he's trying to get open access
> papers more cited in Wikipedia. One part of his project requires a chunk of
> the literature to be searched for information relevant to the wiki page and
> delivered to the editors easily. I'm sure you can see where I'm going with
> this... it feels like The Content Mine pipeline could easily do this around
> various keywords to deliver a stream of facts that could be cited as is, or
> with minimal changes. I keep having Jenny's line about seeing sentences in
> plant paper abstracts as totally copy and pastable into wikipedia running
> through my head. This would be good for you since it's only Open Access
> papers, so no legal barriers, and you'll be developing and supporting
> existing communities that you care about - even better if you're dumping
> the facts in Wikidata. Another interesting possibility, although this is
> getting into a realm I do n't know much about, is automatically creating
> Content Mine feeds for Wikipedia pages from their titles and "sciency"
> words in the introduction."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContentMine/site/issues/232>.
>



-- 
Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by GrahamSteel** [comment]
Happy to help out here, sounds good.

**Comment by jcmolloy** [comment]
Assigning this to @petermr to see if we want to pursue work with Wikimedia/ContentMine

**Comment by jcmolloy** [comment]
To progress making ContentMine useful and integrated with wikidata/Wikipedia @petermr has suggested we ask @Daniel-Mietchen and @magnusmanske to each chose a Wikidata property that we can turn into a dictionary for ContentMine and run across the OA literature on a daily basis. Ideally we could find WD / WP editors knowledgeable in the chosen subject to make use of the extracted facts. @Daniel-Mietchen would this be of interest to your zika group?

**Comment by Daniel-Mietchen** [comment]
Not sure what precisely you have in mind here, but a daily run for a dictionary like 

```
Zika/ Zika virus/ ZIKV/ Zika fever/ flavivirus/ flaviviruses/ Flaviviridae/ Aedes/ Aedes aegypti/ A. aegypti/ Ae. aegypti/ Aedes albopictus/ A. albopictus/ Ae. albopictus/
```

would &mdash; with some useful thresholding &mdash; probably be of interest to the [Zika research](https://groups.google.com/forum/#!forum/zika-research) discussion group.

As for bringing this info into Wikidata, we would probably need many different properties on items around [Q202864 (Zika virus)](https://tools.wmflabs.org/reasonator/?q=Q202864&lang=en), though it should be straightforward to add [P921](https://www.wikidata.org/wiki/Q21144503#P921) statements to items about publications.

**Comment by jcmolloy** [comment]
@JosephMcArthur @Daniel-Mietchen @magnusmanske @petermr I am closing this issue but it is very relevant to our Wikimedia Project Application '[WikiFactMine](https://meta.wikimedia.org/wiki/Grants:Project/WikiFactMine)' and we could continue discussion on the talk page there,

@petermr - could you ping Ed Sapeira with the link to our proposal and start a discussion on the[ Open Access Reader wiki page](https://meta.wikimedia.org/wiki/Talk:Open_Access_Reader)?
