### ISSUE TITLE
filetypes documentation

### ISSUE THREAD

**Issue by Treblesteph** [ContentMine/old_site#71]
- [ ] make page on site about filetypes in docs
- [ ] summary sentence on each filetype
- [ ] link to SVG/XML/PDF tutorials / wikipedia
- [ ] for XML
   - [ ] why is XML preferred format?
   - [ ] what standards exist for scholarly publishing in XML (JATS/NLM)
   - [ ] which publishers provide XML and do they stick to standards
   - [ ] is XML available freely or if you have to agree to something first
   - [ ] could have a table of publishers and whether they provide XML, what format, sign agreement, website or API etc
- [ ] for PDF
   - [ ] PDF standard format for digital scholarship
   - [ ] PDFs destroy information - how?
   - [ ] tools for extracting info from PDFs
   - [ ] advice on how to avoid PDFs

**Comment by jcmolloy** [comment]
Reassigning to @chreman to check these things are necessary (and if so included) in  new workshop materials

**Comment by jcmolloy** [comment]
Closing as very old issue
