### ISSUE TITLE
Checklist for Workshops

### ISSUE THREAD

**Issue by petermr** [ContentMine/old_site#98]
Create a list of essential and optional materials for workshops. Work with Jenny to make this an ongoing item for all workshops

**Comment by chreman** [comment]
Created two separate checklists for [organizers](https://github.com/ContentMine/workshops/blob/master/checklists/checklist_coordinator.md) and [facilitators](https://github.com/ContentMine/workshops/blob/master/checklists/checklist_facilitators.md)
modules will contain individual checklists as well for steps and resources

update with additional steps from MozFest

**Comment by chreman** [comment]
additional:
- links to external teaching resources (MOOCs, etc) for facilitators
- describe formats (highlight most important meta things)
- lessons learned
- checklists: major / minor / optional
